# autogenerated by txs
#include:latexsym
\bf#S
\cal#S
\em#S
\it#S
\mediumseries#S
\mit#S
\normalshape#S
\pcal#S
\pmit#S
\rm#S
\sc#S
\sf#S
\sl#S
\tt#S
\__hook latexsym#S
\unprocessedoptions-latexsym.sty#S
csnameendcsname#S
latexsym.sty#S
